=== Yosa03-dat/Semantic_Web_Assignemnt_02/student_data.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:uni="https://sab.ac.lk/university/students"
           targetNamespace="https://sab.ac.lk/university/students"
           elementFormDefault="qualified">

    <!-- Root element: a collection of one or more students -->
    <xs:element name="studentRecords">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="student" type="uni:StudentType" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- A single student record -->
    <xs:complexType name="StudentType">
        <xs:sequence>
            <xs:element name="personalInfo" type="uni:PersonalInfoType"/>
            <xs:element name="academicInfo" type="uni:AcademicInfoType"/>
            <xs:element name="courses" type="uni:CoursesType"/>
        </xs:sequence>
        <xs:attribute name="id" type="uni:StudentIdType" use="required"/>
    </xs:complexType>

    <!-- Personal information: primary content -> modelled as elements -->
    <xs:complexType name="PersonalInfoType">
        <xs:sequence>
            <xs:element name="fullName" type="xs:string"/>
            <xs:element name="email" type="uni:EmailType"/>
            <xs:element name="dateOfBirth" type="xs:date"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Academic information: faculty/department/year/semester are compact
         classification metadata -> modelled as attributes -->
    <xs:complexType name="AcademicInfoType">
        <xs:sequence>
            <xs:element name="programme" type="uni:ProgrammeType"/>
        </xs:sequence>
        <xs:attribute name="faculty" type="xs:string" use="required"/>
        <xs:attribute name="department" type="xs:string" use="required"/>
        <xs:attribute name="year" type="uni:AcademicYearType" use="required"/>
        <xs:attribute name="semester" type="uni:SemesterType" use="required"/>
    </xs:complexType>

    <xs:complexType name="ProgrammeType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="code" type="xs:string" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="CoursesType">
        <xs:sequence>
            <xs:element name="course" type="uni:CourseType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <!-- A course: code and credit value are identifiers/metadata -> attributes;
         title, lecturer and grade are primary content -> elements -->
    <xs:complexType name="CourseType">
        <xs:sequence>
            <xs:element name="title" type="xs:string"/>
            <xs:element name="lecturer" type="xs:string"/>
            <xs:element name="grade" type="uni:GradeType"/>
        </xs:sequence>
        <xs:attribute name="code" type="xs:string" use="required"/>
        <xs:attribute name="credits" type="xs:positiveInteger" use="required"/>
    </xs:complexType>

    <!-- Restricted / simple types used for validation -->
    <xs:simpleType name="StudentIdType">
        <xs:restriction base="xs:string">
            <xs:pattern value="S[0-9]{3}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="EmailType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[^@\s]+@[^@\s]+\.[^@\s]+"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="AcademicYearType">
        <xs:restriction base="xs:positiveInteger">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="4"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="SemesterType">
        <xs:restriction base="xs:positiveInteger">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="2"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="GradeType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="A"/>
            <xs:enumeration value="A-"/>
            <xs:enumeration value="B+"/>
            <xs:enumeration value="B"/>
            <xs:enumeration value="B-"/>
            <xs:enumeration value="C+"/>
            <xs:enumeration value="C"/>
            <xs:enumeration value="C-"/>
            <xs:enumeration value="D"/>
            <xs:enumeration value="E"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== Yosa03-dat/Semantic_Web_Assignemnt_02/student_data.xml
<?xml version="1.0" encoding="UTF-8"?>
<uni:studentRecords
    xmlns:uni="https://sab.ac.lk/university/students"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://sab.ac.lk/university/students student_data.xsd">

    <uni:student id="S001">
        <uni:personalInfo>
            <uni:fullName>Kamal Perera</uni:fullName>
            <uni:email>kamal.perera@sab.ac.lk</uni:email>
            <uni:dateOfBirth>2002-05-14</uni:dateOfBirth>
        </uni:personalInfo>
        <uni:academicInfo faculty="Faculty of Computing" department="Department of Computing" year="3" semester="1">
            <uni:programme code="DS">BSc (Hons) in Data Science</uni:programme>
        </uni:academicInfo>
        <uni:courses>
            <uni:course code="DS5103" credits="2">
                <uni:title>Semantic Web</uni:title>
                <uni:lecturer>Dr. Kavinda Silva</uni:lecturer>
                <uni:grade>A</uni:grade>
            </uni:course>
            <uni:course code="DS4101" credits="3">
                <uni:title>Advanced Database Management Systems</uni:title>
                <uni:lecturer>Dr. Nadeesha Fernando</uni:lecturer>
                <uni:grade>A-</uni:grade>
            </uni:course>
            <uni:course code="SE8111" credits="3">
                <uni:title>Artificial Intelligence</uni:title>
                <uni:lecturer>Dr. Kavinda Silva</uni:lecturer>
                <uni:grade>B+</uni:grade>
            </uni:course>
        </uni:courses>
    </uni:student>

    <uni:student id="S002">
        <uni:personalInfo>
            <uni:fullName>Nimasha Dilrukshi</uni:fullName>
            <uni:email>nimasha.dilrukshi@sab.ac.lk</uni:email>
            <uni:dateOfBirth>2001-11-02</uni:dateOfBirth>
        </uni:personalInfo>
        <uni:academicInfo faculty="Faculty of Computing" department="Department of Computing" year="4" semester="1">
            <uni:programme code="SE">BSc (Hons) in Software Engineering</uni:programme>
        </uni:academicInfo>
        <uni:courses>
            <uni:course code="SE8111" credits="3">
                <uni:title>Artificial Intelligence</uni:title>
                <uni:lecturer>Dr. Kavinda Silva</uni:lecturer>
                <uni:grade>A</uni:grade>
            </uni:course>
            <uni:course code="SE8202" credits="2">
                <uni:title>Software Project Management</uni:title>
                <uni:lecturer>Mr. Ruwan Jayasena</uni:lecturer>
                <uni:grade>B</uni:grade>
            </uni:course>
        </uni:courses>
    </uni:student>

    <uni:student id="S003">
        <uni:personalInfo>
            <uni:fullName>Ashen Bandara</uni:fullName>
            <uni:email>ashen.bandara@sab.ac.lk</uni:email>
            <uni:dateOfBirth>2002-02-27</uni:dateOfBirth>
        </uni:personalInfo>
        <uni:academicInfo faculty="Faculty of Computing" department="Department of Information Systems" year="2" semester="2">
            <uni:programme code="IS">BSc (Hons) in Information Systems</uni:programme>
        </uni:academicInfo>
        <uni:courses>
            <uni:course code="IS4107" credits="2">
                <uni:title>Professionalism and Ethics in Computing</uni:title>
                <uni:lecturer>Mrs. Chathurika Perera</uni:lecturer>
                <uni:grade>A</uni:grade>
            </uni:course>
            <uni:course code="IS4210" credits="3">
                <uni:title>Business Intelligence</uni:title>
                <uni:lecturer>Dr. Nadeesha Fernando</uni:lecturer>
                <uni:grade>A</uni:grade>
            </uni:course>
        </uni:courses>
    </uni:student>

    <uni:student id="S004">
        <uni:personalInfo>
            <uni:fullName>Thilini Wickramasinghe</uni:fullName>
            <uni:email>thilini.wickramasinghe@sab.ac.lk</uni:email>
            <uni:dateOfBirth>2003-08-19</uni:dateOfBirth>
        </uni:personalInfo>
        <uni:academicInfo faculty="Faculty of Computing" department="Department of Computing" year="1" semester="2">
            <uni:programme code="DS">BSc (Hons) in Data Science</uni:programme>
        </uni:academicInfo>
        <uni:courses>
            <uni:course code="DS1101" credits="3">
                <uni:title>Introduction to Programming</uni:title>
                <uni:lecturer>Mr. Ruwan Jayasena</uni:lecturer>
                <uni:grade>B+</uni:grade>
            </uni:course>
        </uni:courses>
    </uni:student>

    <uni:student id="S005">
        <uni:personalInfo>
            <uni:fullName>Dinuka Rathnayake</uni:fullName>
            <uni:email>dinuka.rathnayake@sab.ac.lk</uni:email>
            <uni:dateOfBirth>2001-06-30</uni:dateOfBirth>
        </uni:personalInfo>
        <uni:academicInfo faculty="Faculty of Computing" department="Department of Computing" year="4" semester="1">
            <uni:programme code="DS">BSc (Hons) in Data Science</uni:programme>
        </uni:academicInfo>
        <uni:courses>
            <uni:course code="DS5103" credits="2">
                <uni:title>Semantic Web</uni:title>
                <uni:lecturer>Dr. Kavinda Silva</uni:lecturer>
                <uni:grade>B</uni:grade>
            </uni:course>
            <uni:course code="DS4101" credits="3">
                <uni:title>Advanced Database Management Systems</uni:title>
                <uni:lecturer>Dr. Nadeesha Fernando</uni:lecturer>
                <uni:grade>B+</uni:grade>
            </uni:course>
        </uni:courses>
    </uni:student>

</uni:studentRecords>
